language: objective-c
os: osx
osx_image: xcode7
xcode_project: APNGKit.xcodeproj
xcode_scheme: APNGKit

script: xcodebuild -project APNGKit.xcodeproj -scheme APNGKit -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' test

git:
  submodules: false
