language: objective-c
os: osx
osx_image: xcode10

env:
  matrix:
    - TEST_TYPE=iOS
    - TEST_TYPE=macOS
script: 
- |
    if [ "$TEST_TYPE" = iOS ]; then
      set -o pipefail
      xcodebuild clean test -workspace APNGKit.xcworkspace -scheme APNGKit-iOS -destination 'platform=iOS Simulator,name=iPhone 7,OS=latest' | xcpretty
    elif [ "$TEST_TYPE" = macOS ]; then
      set -o pipefail
      xcodebuild clean test -workspace APNGKit.xcworkspace -scheme APNGKit-macOS -sdk macosx | xcpretty
    fi
git:
  submodules: false
